[server]
port = 8080
address = "localhost"


[browser]
serverAddress = "localhost"
serverPort = 8080

[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA" 